[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimulatedNeuralMoments = "43b7c8c0-5622-45b8-90a3-338fc50d2232"
SolveDSGE = "00bf1f32-23ad-54cc-bf6e-3216db8a43a2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
